POST http://localhost:4000/api/chats 
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjUxNzFmYjhjMmEyNDVmMzNjNTExYTUwIiwicm9sZSI6ImNsaWVudCJ9LCJpYXQiOjE2OTYwMTQ0MDUsImV4cCI6MTY5NjEwMDgwNX0.zUkzc0glDh1KXvC-OiesnwgPcMn1SsjgSIh4V7wOtR8
Content-Type: application/json

{
    "text":"Assalomu alaykum"
}

# 651721abb04aa9b26e5c4bbe

###
GET http://localhost:4000/api/chats/651721abb04aa9b26e5c4bbe
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRkZmI2OTljN2VhODZjNDAzN2NiYmY4Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NTk2Mjg3NiwiZXhwIjoxNjk2MDQ5Mjc2fQ.jMC6iLUDqjfNjIymEPb7E5LJwFIacFWwC0o9HcCEPzo

###
GET http://localhost:4000/api/chats
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRkZmI2OTljN2VhODZjNDAzN2NiYmY4Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NTk2Mjg3NiwiZXhwIjoxNjk2MDQ5Mjc2fQ.jMC6iLUDqjfNjIymEPb7E5LJwFIacFWwC0o9HcCEPzo

