
GET http://localhost:4000/api/devices
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRkZmI2OTljN2VhODZjNDAzN2NiYmY4Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NTk4MzMxMCwiZXhwIjoxNjk2MDY5NzEwfQ.QWSWEr4wlQqRXo6_R0LTXECXLCZimlndjX5CzCRKDoY


###
GET http://localhost:4000/api/devices/65166fac3b362ef26dfbabbe
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRkZmI2OTljN2VhODZjNDAzN2NiYmY4Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NTk4MzMxMCwiZXhwIjoxNjk2MDY5NzEwfQ.QWSWEr4wlQqRXo6_R0LTXECXLCZimlndjX5CzCRKDoY


###
GET http://localhost:4000/api/edibles
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRkZmI2OTljN2VhODZjNDAzN2NiYmY4Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NTk4MzMxMCwiZXhwIjoxNjk2MDY5NzEwfQ.QWSWEr4wlQqRXo6_R0LTXECXLCZimlndjX5CzCRKDoY

###
GET http://localhost:4000/api/edibles/6516708b3b362ef26dfbac1a
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRkZmI2OTljN2VhODZjNDAzN2NiYmY4Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NTk4MzMxMCwiZXhwIjoxNjk2MDY5NzEwfQ.QWSWEr4wlQqRXo6_R0LTXECXLCZimlndjX5CzCRKDoY


###
DELETE  http://localhost:4000/api/products/65166fac3b362ef26dfbabbe
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRkZmI2OTljN2VhODZjNDAzN2NiYmY4Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NTk4MzMxMCwiZXhwIjoxNjk2MDY5NzEwfQ.QWSWEr4wlQqRXo6_R0LTXECXLCZimlndjX5CzCRKDoY
