POST http://localhost:4000/api/teachers
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRkZmI2OTljN2VhODZjNDAzN2NiYmY4Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NTk4MzMxMCwiZXhwIjoxNjk2MDY5NzEwfQ.QWSWEr4wlQqRXo6_R0LTXECXLCZimlndjX5CzCRKDoY
Content-Type: application/json

{   
    "first_name":"Ustoz",
    "last_name":"Ustoz",
    "birthday":"01.03.2004",
    "email":"teacher0@gmail.com",
    "password":"123456",
    "phone":998880827612,
    "gender":"ayol",
    "info":"dwdwd",
    "kun":"juft",
    "category":2
}


####
GET http://localhost:4000/api/teachers
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRkZmI2OTljN2VhODZjNDAzN2NiYmY4Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NTk4MzMxMCwiZXhwIjoxNjk2MDY5NzEwfQ.QWSWEr4wlQqRXo6_R0LTXECXLCZimlndjX5CzCRKDoY



####
GET http://localhost:4000/api/teachers/6516c124f54dee99ce36ee8c
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRkZmI2OTljN2VhODZjNDAzN2NiYmY4Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NTk4MzMxMCwiZXhwIjoxNjk2MDY5NzEwfQ.QWSWEr4wlQqRXo6_R0LTXECXLCZimlndjX5CzCRKDoY

####
DELETE  http://localhost:4000/api/teachers/6516c12bf54dee99ce36ee94
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRkZmI2OTljN2VhODZjNDAzN2NiYmY4Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NTk4MzMxMCwiZXhwIjoxNjk2MDY5NzEwfQ.QWSWEr4wlQqRXo6_R0LTXECXLCZimlndjX5CzCRKDoY


###

PATCH   http://localhost:4000/api/teachers/6516c124f54dee99ce36ee8c
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiNjRkZmI2OTljN2VhODZjNDAzN2NiYmY4Iiwicm9sZSI6ImFkbWluIn0sImlhdCI6MTY5NTk4MzMxMCwiZXhwIjoxNjk2MDY5NzEwfQ.QWSWEr4wlQqRXo6_R0LTXECXLCZimlndjX5CzCRKDoY
Content-Type: application/json

{   
    "first_name":"Nurbek",
    "last_name":"Mo'minov"
}